#!/usr/bin/env python3
"""Post placeholder digest thread so it appears as the first comment on the PR.

Usage:
    python post-digest-placeholder.py <pr_url> <platform> [--workspace-dir <path>]

Outputs JSON with thread_id (if ADO) and injects a digest link into the PR description.
"""
import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path


try:
    from pr_platform import DigestOps, PrBodyOps, PrRef
except ImportError:
    DigestOps = None
    PrBodyOps = None
    PrRef = None

marker = "<!-- ai-agent:pr-orchestrator-digest -->"
placeholder = (
    marker + "\n"
    "# PR Orchestrator — Review Digest\n\n"
    "> ⏳ **Validation in progress** — this digest will be updated "
    "automatically when all phases complete.\n\n"
    "<sub>Generated by [PR Orchestrator](https://github.com/azure-core/octane)</sub>\n"
)


def _resolve_workspace_dir(workspace_dir: str | None) -> Path:
    if workspace_dir:
        path = Path(workspace_dir)
        path.mkdir(parents=True, exist_ok=True)
        return path

    fallback = Path(tempfile.gettempdir())
    print(
        "WARNING: --workspace-dir not provided; falling back to the shared temp directory",
        file=sys.stderr,
    )
    return fallback


def main() -> int:
    parser = argparse.ArgumentParser(description="Post placeholder digest thread")
    parser.add_argument("pr_url")
    parser.add_argument("platform")
    parser.add_argument("--workspace-dir", default="", help="Directory for per-run workspace artifacts")
    args = parser.parse_args()

    workspace_dir = _resolve_workspace_dir(args.workspace_dir)
    content_file = workspace_dir / "digest-placeholder.md"
    content_file.write_text(placeholder, encoding="utf-8")

    home = os.environ.get("USERPROFILE") or os.path.expanduser("~")
    upsert = os.path.join(
        home, ".copilot", "installed-plugins", "octane",
        "octane-pr-orchestrator", "skills", "deterministic-scripts",
        "scripts", "upsert-digest.py",
    )

    pr_url = args.pr_url
    plat = args.platform
    cmd = [
        sys.executable,
        upsert,
        "--platform",
        plat,
        "--pr-url",
        pr_url,
        "--content-file",
        str(content_file),
        "--workspace-dir",
        str(workspace_dir),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    if result.returncode != 0:
        sys.stdout.write(result.stdout)
        sys.stderr.write(result.stderr)
        return result.returncode

    try:
        upsert_out = json.loads(result.stdout)
    except (json.JSONDecodeError, AttributeError):
        upsert_out = None

    updated_via_abstraction = False
    if isinstance(upsert_out, dict) and DigestOps and PrBodyOps and PrRef:
        try:
            ref = PrRef.from_url(pr_url)
            digest_ops = DigestOps(ref)
            body_ops = PrBodyOps(ref)
            thread_id = str(upsert_out.get("thread_id", ""))
            comment_id = str(upsert_out.get("comment_id", ""))

            if ref.platform == "ado" and thread_id:
                digest_url = digest_ops.comment_url(thread_id)
            elif ref.platform == "github" and comment_id:
                digest_url = digest_ops.comment_url(comment_id, comment_id)
            else:
                digest_url = ""

            if digest_url:
                upsert_out["digest_comment_url"] = digest_url
                digest_link = f"\n\n> 📋 **[Review Digest]({digest_url})** — automated validation summary for reviewers\n"
                desc = body_ops.fetch() or ""
                if digest_url not in desc:
                    if "{{DIGEST_COMMENT_URL}}" in desc:
                        desc = desc.replace("{{DIGEST_COMMENT_URL}}", digest_url)
                    elif "DIGEST_LINK_PLACEHOLDER" in desc:
                        desc = desc.replace("DIGEST_LINK_PLACEHOLDER", digest_url)
                    elif "<!-- pr-orchestrator -->" in desc:
                        desc = desc.replace("<!-- pr-orchestrator -->", "<!-- pr-orchestrator -->" + digest_link, 1)
                    else:
                        desc = digest_link + desc
                    body_ops.update(desc)
                updated_via_abstraction = True
        except Exception:
            updated_via_abstraction = False

    if isinstance(upsert_out, dict) and not updated_via_abstraction:
        thread_id = upsert_out.get("thread_id", "")
        if thread_id and plat == "ado":
            digest_url = pr_url.rstrip("/") + "?discussionId=" + str(thread_id)
            upsert_out["digest_comment_url"] = digest_url
            digest_link = f"\n\n> 📋 **[Review Digest]({digest_url})** — automated validation summary for reviewers\n"

            m = re.match(r"https://(?:dev\.azure\.com|msazure\.visualstudio\.com)/([^/]+)/([^/]+)/_git/([^/]+)/pullrequest/(\d+)", pr_url)
            if m:
                org, project, repo, pr_id = m.groups()
                base = f"https://dev.azure.com/{org}" if "dev.azure.com" in pr_url else f"https://{org}.visualstudio.com"
                api = f"{base}/{project}/_apis/git/repositories/{repo}/pullRequests/{pr_id}?api-version=7.1"
                resource = "499b84ac-1321-427f-aa17-267ca6975798"

                desc_file = workspace_dir / "pr-desc-fetch.json"
                fetch = subprocess.run(
                    ["az", "rest", "--method", "get", "--url", api, "--resource", resource, "--output-file", str(desc_file)],
                    capture_output=True, text=True, timeout=30,
                )
                if fetch.returncode == 0 and desc_file.exists():
                    with open(desc_file, "r", encoding="utf-8") as f:
                        pr_data = json.load(f)
                    desc = pr_data.get("description", "") or ""

                    if "discussionId=" not in desc:
                        if "{{DIGEST_COMMENT_URL}}" in desc:
                            desc = desc.replace("{{DIGEST_COMMENT_URL}}", digest_url)
                        elif "<!-- pr-orchestrator -->" in desc:
                            desc = desc.replace("<!-- pr-orchestrator -->", "<!-- pr-orchestrator -->" + digest_link, 1)
                        else:
                            desc = digest_link + desc

                        body_file = workspace_dir / "pr-desc-patch.json"
                        body_file.write_text(json.dumps({"description": desc}), encoding="utf-8")
                        subprocess.run(
                            ["az", "rest", "--method", "patch", "--url", api, "--resource", resource,
                             "--body", f"@{body_file}", "--headers", "Content-Type=application/json"],
                            capture_output=True, text=True, timeout=30,
                        )
        elif plat == "github":
            comment_id = upsert_out.get("comment_id", "")
            if comment_id:
                digest_url = pr_url.rstrip("/") + "#issuecomment-" + str(comment_id)
                upsert_out["digest_comment_url"] = digest_url
                digest_link = f"\n\n> 📋 **[Review Digest]({digest_url})** — automated validation summary for reviewers\n"
                gh_m = re.match(r"https://github\.com/([^/]+)/([^/]+)/pull/(\d+)", pr_url)
                if gh_m:
                    gh_owner, gh_repo, gh_pr = gh_m.groups()
                    fetch_result = subprocess.run(
                        ["gh", "pr", "view", gh_pr, "--repo", f"{gh_owner}/{gh_repo}", "--json", "body"],
                        capture_output=True, text=True, timeout=30,
                    )
                    if fetch_result.returncode == 0:
                        try:
                            pr_data = json.loads(fetch_result.stdout)
                            desc = pr_data.get("body", "") or ""
                            if "issuecomment-" not in desc:
                                if "DIGEST_LINK_PLACEHOLDER" in desc:
                                    desc = desc.replace("DIGEST_LINK_PLACEHOLDER", digest_url)
                                elif "<!-- pr-orchestrator -->" in desc:
                                    desc = desc.replace("<!-- pr-orchestrator -->", "<!-- pr-orchestrator -->" + digest_link, 1)
                                else:
                                    desc = digest_link + desc

                                body_file_gh = workspace_dir / "pr-desc-gh.md"
                                body_file_gh.write_text(desc, encoding="utf-8")
                                subprocess.run(
                                    ["gh", "pr", "edit", gh_pr, "--repo", f"{gh_owner}/{gh_repo}",
                                     "--body-file", str(body_file_gh)],
                                    capture_output=True, text=True, timeout=30,
                                )
                        except (json.JSONDecodeError, KeyError):
                            pass

    sys.stdout.write(json.dumps(upsert_out) if isinstance(upsert_out, dict) else result.stdout)
    return 0


if __name__ == "__main__":
    sys.exit(main())
