# Generated by AI (PR Orchestrator)
import copy
import json
import subprocess
import sys
import uuid
from dataclasses import dataclass, field
from importlib.util import module_from_spec, spec_from_file_location
from pathlib import Path
from shutil import copy2
from typing import Any

import pytest

SCRIPTS_DIR = Path(__file__).parent


REALISTIC_PHASE_OUTPUTS = {
    "1a": {
        "business_logic_digest": "Business logic digest for PR Orchestrator",
        "test_coverage_digest": "Coverage digest for PR Orchestrator",
        "tests_run": 12,
        "tests_passed": 12,
        "tests_failed": 0,
    },
    "1b": {
        "test_generation_result": {
            "generated": 2,
            "passing": 2,
            "notes": ["Added regression coverage for phase driver"],
        }
    },
    "1c": {
        "code_review_findings": {"high": [], "medium": [], "low": []},
        "tier": "critical",
        "review_engine": "mock-conductor",
    },
    "1d": {
        "code_fix": "No mechanical findings to apply.",
        "fixes_applied": 0,
        "findings_remaining": 0,
    },
    "2": {
        "pr_url": "https://dev.azure.com/example/project/_git/repo/pullrequest/42",
        "pr_title": "PR Orchestrator reliability refactor",
        "work_items_linked": ["12345"],
    },
    "3": {
        "build_status": "green",
        "fixes_pushed": 0,
        "elapsed_minutes": 1,
    },
    "4": {
        "digest_comment_url": "https://dev.azure.com/example/project/_git/repo/pullrequest/42?discussionId=99",
        "digest_comment_id": "99:1",
    },
    "5": {
        "address_feedback": "done",
        "comments_addressed": 3,
        "comments_remaining": 0,
        "all_addressed": True,
        "status": "completed",
        "iteration": 1,
    },
}


EXPECTED_YOLO_FAST_PHASES = ["1a", "1b", "1c", "2", "4", "5"]
EXPECTED_COMPLETED_YOLO_FAST_PHASES = ["1a", "1b", "1c", "1d", "2", "4", "5"]
PHASE_EXPECTED_KEYS = {
    "1a": {"business_logic_digest", "test_coverage_digest", "tests_run", "tests_passed", "tests_failed"},
    "1b": {"test_generation_result"},
    "1c": {"code_review_findings", "tier", "review_engine"},
    "2": {"pr_url", "pr_title", "work_items_linked"},
    "4": {"digest_comment_url", "digest_comment_id"},
    "5": {"address_feedback", "comments_addressed", "comments_remaining", "all_addressed", "status", "iteration"},
}


@dataclass
class MockConductor:
    event_dir: Path
    outputs: dict[str, dict[str, Any]] = field(default_factory=lambda: copy.deepcopy(REALISTIC_PHASE_OUTPUTS))
    actions: dict[str, list[str]] = field(default_factory=dict)
    calls: list[dict[str, Any]] = field(default_factory=list)

    def action_for(self, phase_id: str, attempt: int) -> str:
        plan = self.actions.get(phase_id, [])
        if attempt < len(plan):
            return plan[attempt]
        return "success"

    def payload_for(self, phase_id: str) -> dict[str, Any]:
        return copy.deepcopy(self.outputs.get(phase_id, {}))

    def write_event_log(self, workflow_path: Path, phase_id: str, attempt: int, action: str) -> str:
        event_file = self.event_dir / f"conductor-{workflow_path.stem}-{phase_id}-{attempt}.events.jsonl"
        if action == "timeout":
            return str(event_file)

        payload = self.payload_for(phase_id)
        if action == "invalid_json":
            event_file.write_text('{"type":"workflow_completed","data":{"output":', encoding="utf-8")
            return str(event_file)

        if action == "missing_output":
            payload = {}

        lines = [
            json.dumps({"type": "workflow_started", "data": {"phase": phase_id}}),
            json.dumps({"type": "workflow_completed", "data": {"output": payload}}),
        ]
        event_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return str(event_file)

    def run(
        self,
        workflow_path: Path,
        inputs: dict[str, str],
        conductor_flags: list[str],
        run_id: str,
        phase_id: str,
        attempt: int,
        work_dir: Path,
        timeout_s: int = 1800,
    ) -> tuple[int, str]:
        action = self.action_for(phase_id, attempt)
        event_log = self.write_event_log(workflow_path, phase_id, attempt, action)
        self.calls.append(
            {
                "phase_id": phase_id,
                "attempt": attempt,
                "workflow": workflow_path.name,
                "inputs": dict(inputs),
                "flags": list(conductor_flags),
                "run_id": run_id,
                "work_dir": str(work_dir),
                "timeout_s": timeout_s,
                "action": action,
                "event_log": event_log,
            }
        )
        if action == "fail":
            return 1, event_log
        if action == "timeout":
            return 124, event_log
        return 0, event_log


class PipelineHarness:
    def __init__(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
        self.tmp_path = tmp_path
        self.monkeypatch = monkeypatch
        self.plugin_root = self._create_plugin_tree()
        self.state_file = tmp_path / "pipeline-state.json"
        self.workspace_root = tmp_path / "workspaces"
        self.workspace_root.mkdir(parents=True, exist_ok=True)
        self.mock = MockConductor(tmp_path / "conductor")
        self.mock.event_dir.mkdir(parents=True, exist_ok=True)
        self.state_snapshots: dict[str, dict[str, Any]] = {}
        self.compute_fingerprint_value: dict[str, str] = {}
        self.mod = self._load_run_phases()
        self._patch_module()

    def _create_plugin_tree(self) -> Path:
        plugin_root = self.tmp_path / ".copilot" / "installed-plugins" / "octane" / "octane-pr-orchestrator"
        workflow_dir = plugin_root / "workflows"
        scripts_dir = plugin_root / "skills" / "deterministic-scripts" / "scripts"
        workflow_dir.mkdir(parents=True, exist_ok=True)
        scripts_dir.mkdir(parents=True, exist_ok=True)

        for workflow in [
            "phase1a-digests.yaml",
            "phase1b-testgen.yaml",
            "phase1c-codereview.yaml",
            "phase1d-codefix.yaml",
            "phase2-create-pr.yaml",
            "phase3-watch-fix.yaml",
            "phase4-review-digest.yaml",
            "phase5-feedback.yaml",
        ]:
            (workflow_dir / workflow).write_text("# workflow stub\n", encoding="utf-8")

        for script_name in ("merge-state.py", "phase_contracts.py", "encoding_utils.py"):
            copy2(SCRIPTS_DIR / script_name, scripts_dir / script_name)

        return plugin_root

    def _load_run_phases(self):
        module_name = f"run_phases_e2e_{uuid.uuid4().hex}"
        spec = spec_from_file_location(module_name, str(SCRIPTS_DIR / "run-phases.py"))
        mod = module_from_spec(spec)
        sys.path.insert(0, str(SCRIPTS_DIR)) if str(SCRIPTS_DIR) not in sys.path else None
        spec.loader.exec_module(mod)
        return mod

    def _patch_module(self) -> None:
        self.monkeypatch.setenv("USERPROFILE", str(self.tmp_path))
        self.monkeypatch.setattr(self.mod, "compute_fingerprint", lambda pr_url=None: dict(self.compute_fingerprint_value))
        self.monkeypatch.setattr(self.mod, "_create_pr_body", lambda *args, **kwargs: None)
        self.monkeypatch.setattr(self.mod, "_update_pr_body", lambda *args, **kwargs: None)

        def create_workspace_dir(run_id: str, workspace_dir: Path | None = None) -> Path:
            workspace = Path(workspace_dir) if workspace_dir else self.workspace_root / run_id
            workspace.mkdir(parents=True, exist_ok=True)
            return workspace

        self.monkeypatch.setattr(self.mod, "create_workspace_dir", create_workspace_dir)
        self.monkeypatch.setattr(self.mod, "run_conductor", self.mock.run)

        original_merge = self.mod.run_merge_state

        def wrapped_merge(*args, **kwargs):
            rc = original_merge(*args, **kwargs)
            phase_id = kwargs.get("phase_id")
            state_file = Path(kwargs.get("state_file"))
            if phase_id and state_file.exists():
                self.state_snapshots[phase_id] = self.mod.load_state(state_file)
            return rc

        self.monkeypatch.setattr(self.mod, "run_merge_state", wrapped_merge)

        original_subprocess_run = subprocess.run

        def fake_subprocess_run(cmd, *args, **kwargs):
            command_list = list(cmd) if isinstance(cmd, (list, tuple)) else [cmd]
            if command_list[:3] == ["git", "branch", "--show-current"]:
                return subprocess.CompletedProcess(command_list, 0, stdout="users/toddrob/pr-orchestrator-finishes\n", stderr="")
            if len(command_list) >= 2 and Path(str(command_list[1])).name == "merge-state.py":
                return original_subprocess_run(command_list, *args, **kwargs)
            raise AssertionError(f"Unexpected subprocess.run call: {command_list}")

        self.monkeypatch.setattr(self.mod.subprocess, "run", fake_subprocess_run)

    def run_pipeline(
        self,
        *,
        mode: str = "yolo-fast",
        initial_state: dict[str, Any] | None = None,
        resume: bool = False,
        skip_next: bool = False,
    ) -> dict[str, Any]:
        if initial_state is not None:
            self.state_file.write_text(json.dumps(initial_state, indent=2), encoding="utf-8")
        elif self.state_file.exists():
            self.state_file.unlink()

        try:
            return self.mod.run_pipeline(
                mode=mode,
                target_branch="main",
                work_dir=self.tmp_path,
                resume=resume,
                skip_next=skip_next,
                state_file_override=self.state_file,
            )
        except SystemExit as exc:
            paused_state = self.mod.load_state(self.state_file)
            return {
                "status": "paused",
                "_exit_code": exc.code,
                **paused_state,
            }

    def run_single_phase(
        self,
        phase_id: str,
        *,
        initial_state: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        if initial_state is not None:
            self.state_file.write_text(json.dumps(initial_state, indent=2), encoding="utf-8")
        elif self.state_file.exists():
            self.state_file.unlink()

        return self.mod.run_single_phase(
            phase_id=phase_id,
            target_branch="main",
            work_dir=self.tmp_path,
            state_file_override=self.state_file,
        )

    def load_state(self) -> dict[str, Any]:
        return json.loads(self.state_file.read_text(encoding="utf-8"))


@pytest.fixture
def harness(tmp_path, monkeypatch) -> PipelineHarness:
    return PipelineHarness(tmp_path, monkeypatch)


def test_happy_path_yolo_fast_accumulates_realistic_phase_outputs(harness: PipelineHarness):
    result = harness.run_pipeline(mode="yolo-fast")

    assert result["status"] == "completed"
    final_state = harness.load_state()
    assert final_state["_completed_phases"] == EXPECTED_COMPLETED_YOLO_FAST_PHASES
    assert set(final_state["_phases"]) == set(EXPECTED_YOLO_FAST_PHASES)
    assert final_state["_phases"]["4"]["digest_comment_url"].startswith("https://dev.azure.com/")
    assert final_state["_phases"]["5"]["all_addressed"] is True


def test_yolo_fast_runs_phases_in_expected_order(harness: PipelineHarness):
    result = harness.run_pipeline(mode="yolo-fast")

    assert result["status"] == "completed"
    assert [call["phase_id"] for call in harness.mock.calls] == EXPECTED_YOLO_FAST_PHASES


def test_state_accumulates_under_phase_namespace_after_each_merge(harness: PipelineHarness):
    result = harness.run_pipeline(mode="yolo-fast")

    assert result["status"] == "completed"
    for phase_id, expected_keys in PHASE_EXPECTED_KEYS.items():
        snapshot = harness.state_snapshots[phase_id]
        assert expected_keys.issubset(snapshot["_phases"][phase_id].keys())


def test_conductor_failure_retries_and_pipeline_recovers(harness: PipelineHarness):
    harness.mock.actions = {"1c": ["fail", "success"]}

    result = harness.run_pipeline(mode="yolo-fast")

    phase_calls = [call for call in harness.mock.calls if call["phase_id"] == "1c"]
    assert result["status"] == "completed"
    assert len(phase_calls) == 2
    assert [call["attempt"] for call in phase_calls] == [0, 1]


def test_conductor_timeout_fails_cleanly_after_retries(harness: PipelineHarness):
    harness.mock.actions = {"2": ["timeout", "timeout", "timeout"]}

    result = harness.run_pipeline(mode="yolo-fast")

    phase_calls = [call for call in harness.mock.calls if call["phase_id"] == "2"]
    assert result["status"] == "failed"
    assert len(phase_calls) == 3
    assert result["phases"]["2"]["error"] == "Conductor exited with code 124"
    assert "4" not in result["phases"]


def test_corrupt_state_file_is_recovered_on_fresh_run(harness: PipelineHarness):
    harness.state_file.write_text("{ not valid json", encoding="utf-8")

    result = harness.run_pipeline(mode="yolo-fast")

    assert result["status"] == "completed"
    recovered_state = harness.load_state()
    assert recovered_state["_completed_phases"] == EXPECTED_COMPLETED_YOLO_FAST_PHASES


def test_phase_four_blocks_without_required_pr_url_state(harness: PipelineHarness):
    initial_state = {
        "_completed_phases": ["1a", "1b", "1c"],
        "_phases": {
            "1a": copy.deepcopy(REALISTIC_PHASE_OUTPUTS["1a"]),
            "1b": copy.deepcopy(REALISTIC_PHASE_OUTPUTS["1b"]),
            "1c": copy.deepcopy(REALISTIC_PHASE_OUTPUTS["1c"]),
        },
    }

    result = harness.run_single_phase("4", initial_state=initial_state)

    assert result["status"] == "error"
    assert "pr_url" in result["error"]
    assert harness.mock.calls == []


def test_matching_fingerprint_and_completed_phase_skip_rerun_on_resume(harness: PipelineHarness):
    harness.compute_fingerprint_value = {"pr_head": "abc123", "base_sha": "def456"}
    initial_state = {
        "_completed_phases": ["1a"],
        "_pending_gate": "1a",
        "_gate_message": "Digests complete.",
        "_run_id": "resume-run",
        "_started_at": "2026-01-01T00:00:00+00:00",
        "_phase_results": {"1a": {"status": "completed", "duration_s": 1.0, "attempts": 1}},
        "_phase_meta": {"1a": {"fingerprint": {"pr_head": "abc123", "base_sha": "def456"}}},
        "_phases": {"1a": copy.deepcopy(REALISTIC_PHASE_OUTPUTS["1a"])},
    }

    result = harness.run_pipeline(mode="interactive", initial_state=initial_state, resume=True)

    assert result["status"] == "paused"
    executed = [call["phase_id"] for call in harness.mock.calls]
    assert "1a" not in executed
    assert executed[0] == "1b"


def test_resume_after_interruption_only_runs_remaining_phases(harness: PipelineHarness):
    initial_state = {
        "_completed_phases": ["1a", "1b", "1c"],
        "_pending_gate": "1c",
        "_gate_message": "Review complete.",
        "_run_id": "resume-run",
        "_started_at": "2026-01-01T00:00:00+00:00",
        "_phase_results": {
            "1a": {"status": "completed", "duration_s": 1.0, "attempts": 1},
            "1b": {"status": "completed", "duration_s": 1.0, "attempts": 1},
            "1c": {"status": "completed", "duration_s": 1.0, "attempts": 1},
        },
        "_phases": {
            "1a": copy.deepcopy(REALISTIC_PHASE_OUTPUTS["1a"]),
            "1b": copy.deepcopy(REALISTIC_PHASE_OUTPUTS["1b"]),
            "1c": copy.deepcopy(REALISTIC_PHASE_OUTPUTS["1c"]),
        },
    }

    result = harness.run_pipeline(mode="interactive", initial_state=initial_state, resume=True)

    assert result["status"] == "paused"
    executed = [call["phase_id"] for call in harness.mock.calls]
    assert executed == ["2"]
    resumed_state = harness.load_state()
    assert resumed_state["_pending_gate"] == "2"
