#!/usr/bin/env python3
"""Validate PR description matches the PR Orchestrator pr-body.md template.

Detects when bots (e.g., GitOps PR Copilot) overwrite the description while
preserving the sentinel marker.

Usage:
    python validate-pr-description.py < description.md
    python validate-pr-description.py description.md

Output: JSON { "valid": bool, "overwritten_by": str|null, "missing_sections": [...] }
Exit code: 0 if valid, 1 if overwritten or missing sections.
"""

import json
import re
import sys


def read_input():
    if len(sys.argv) > 1:
        with open(sys.argv[1], "r", encoding="utf-8") as f:
            return f.read()
    return sys.stdin.read()


def validate(content: str) -> dict:
    missing = []
    overwritten_by = None

    # 1. Sentinel check
    has_sentinel = "<!-- pr-orchestrator -->" in content

    if not has_sentinel:
        missing.append("<!-- pr-orchestrator --> sentinel")

    # 2. Content markers — these prove our description is still intact
    content_markers = {
        "## Intent": r"^##\s+Intent",
        "## Changes": r"^##\s+Changes",
        "## Validation": r"^##\s+Validation",
    }

    for name, pattern in content_markers.items():
        if not re.search(pattern, content, re.MULTILINE):
            missing.append(name)

    # 3. Detect specific bot overwrites
    if has_sentinel and len(missing) > 0:
        if "GitOpsUserAgent" in content or "GitOps.Apps.Server" in content:
            overwritten_by = "GitOps PR Copilot"
        elif "AI description" in content and "PR Classification" in content:
            overwritten_by = "GitOps PR Copilot (AI description)"
        elif has_sentinel and len(missing) >= 3:
            overwritten_by = "Unknown bot (sentinel preserved, all content sections missing)"

    # 4. Footer check
    has_footer = bool(re.search(r"Generated by \[PR Orchestrator\]", content))
    if not has_footer and has_sentinel:
        missing.append("PR Orchestrator footer")

    valid = has_sentinel and len(missing) == 0

    return {
        "valid": valid,
        "overwritten_by": overwritten_by,
        "missing_sections": missing,
    }


def main():
    content = read_input()
    if not content.strip():
        result = {
            "valid": False,
            "overwritten_by": None,
            "missing_sections": ["Empty input — no description provided"],
        }
    else:
        result = validate(content)

    print(json.dumps(result, indent=2))
    sys.exit(0 if result["valid"] else 1)


if __name__ == "__main__":
    main()
