# Generated by AI (PR Orchestrator)
"""Unit tests for merge_classifications.py."""

import pytest

from merge_classifications import (
    _normalize_field_names,
    _safe_int,
    _safe_line,
    compute_metrics,
    identify_gaps,
    merge_and_validate,
)


class TestSafeLine:
    def test_parses_simple_integer(self):
        assert _safe_line(42) == 42

    def test_parses_string_integer(self):
        assert _safe_line("42") == 42

    def test_parses_range_taking_start(self):
        assert _safe_line("242-243") == 242

    def test_returns_zero_for_none(self):
        assert _safe_line(None) == 0

    def test_returns_zero_for_empty_string(self):
        assert _safe_line("") == 0

    def test_returns_zero_for_non_numeric(self):
        assert _safe_line("abc") == 0

    def test_parses_range_with_spaces(self):
        assert _safe_line("10 - 15") == 10


class TestSafeInt:
    def test_converts_integer(self):
        assert _safe_int(5) == 5

    def test_converts_string_integer(self):
        assert _safe_int("7") == 7

    def test_returns_default_for_none(self):
        assert _safe_int(None) == 0

    def test_returns_custom_default_for_invalid(self):
        assert _safe_int("bad", default=99) == 99

    def test_returns_zero_default_for_empty_string(self):
        assert _safe_int("") == 0


class TestNormalizeFieldNames:
    def test_maps_semantic_score_to_sem(self):
        cls = {"comment_id": "1", "classification": "CAUGHT", "semantic_score": 0.9}
        result = _normalize_field_names(cls)
        assert result["sem"] == 0.9

    def test_maps_total_score_to_score(self):
        cls = {"comment_id": "1", "classification": "CAUGHT", "total_score": 5}
        result = _normalize_field_names(cls)
        assert result["score"] == 5

    def test_maps_rationale_to_reason(self):
        cls = {"comment_id": "1", "classification": "CAUGHT", "rationale": "because"}
        result = _normalize_field_names(cls)
        assert result["reason"] == "because"

    def test_does_not_overwrite_existing_canonical_field(self):
        cls = {"comment_id": "1", "classification": "CAUGHT", "sem": 0.7, "semantic_score": 0.9}
        result = _normalize_field_names(cls)
        assert result["sem"] == 0.7

    def test_maps_kebab_matched_violation_to_matched_guideline(self):
        cls = {"comment_id": "1", "classification": "CAUGHT", "matched_violation": "dead-code"}
        result = _normalize_field_names(cls)
        assert result["matched_guideline"] == "dead-code"

    def test_does_not_map_matched_violation_with_spaces_to_guideline(self):
        cls = {"comment_id": "1", "classification": "CAUGHT", "matched_violation": "some sentence"}
        result = _normalize_field_names(cls)
        assert "matched_guideline" not in result

    def test_normalizes_comment_id_to_string(self):
        cls = {"comment_id": 123, "classification": "CAUGHT"}
        result = _normalize_field_names(cls)
        assert result["comment_id"] == "123"

    def test_returns_same_dict_mutated_in_place(self):
        cls = {"comment_id": "1", "classification": "CAUGHT"}
        result = _normalize_field_names(cls)
        assert result is cls


class TestMergeAndValidate:
    def _comment(self, cid, **kwargs):
        return {"comment_id": str(cid), "comment_body": "body", "line_number": 10,
                "comment_type": "inline", "author": "dev", "file_path": "foo.ts",
                "iteration_id": 1, **kwargs}

    def _classification(self, cid, cls="CAUGHT", **kwargs):
        return {"comment_id": str(cid), "classification": cls, "sem": 0.8, "score": 4,
                "matched_guideline": "rule", **kwargs}

    def test_enriches_classification_with_comment_metadata(self):
        comments = [self._comment(1, file_path="bar.ts")]
        clss = [self._classification(1)]
        result = merge_and_validate(clss, comments, [])
        assert result[0]["file_path"] == "bar.ts"

    def test_auto_miss_unclassified_comments(self):
        comments = [self._comment(1), self._comment(2)]
        clss = [self._classification(1)]  # comment 2 not classified
        result = merge_and_validate(clss, comments, [])
        missed = [r for r in result if r["comment_id"] == "2"]
        assert len(missed) == 1
        assert missed[0]["classification"] == "MISSED"

    def test_auto_miss_comments_on_no_violation_files(self):
        comments = [self._comment(5)]
        clss = []
        result = merge_and_validate(clss, comments, [5])
        assert result[0]["classification"] == "MISSED"
        assert result[0]["reason"] == "No Gatekeeper violations on this file"

    def test_already_classified_comments_not_double_missed(self):
        comments = [self._comment(1)]
        clss = [self._classification(1)]
        result = merge_and_validate(clss, comments, [1])
        assert len([r for r in result if r["comment_id"] == "1"]) == 1

    def test_result_is_sorted_by_iteration_then_file_then_line(self):
        comments = [
            self._comment(1, iteration_id=2, file_path="z.ts", line_number=100),
            self._comment(2, iteration_id=1, file_path="a.ts", line_number=50),
        ]
        clss = [self._classification(1), self._classification(2)]
        result = merge_and_validate(clss, comments, [])
        order = [(r["comment_id"]) for r in result]
        assert order == ["2", "1"]

    def test_empty_inputs_return_empty(self):
        assert merge_and_validate([], [], []) == []


class TestComputeMetrics:
    def _cls(self, classification):
        return {"classification": classification}

    def test_counts_caught_partial_missed(self):
        clss = [self._cls("CAUGHT"), self._cls("CAUGHT"), self._cls("PARTIAL"), self._cls("MISSED")]
        metrics = compute_metrics(clss)
        assert metrics["caught"] == 2
        assert metrics["partial"] == 1
        assert metrics["missed"] == 1

    def test_avoidable_pct_calculation(self):
        # 2 caught + 1 partial out of 4 actionable = 75%
        clss = [self._cls("CAUGHT"), self._cls("CAUGHT"), self._cls("PARTIAL"), self._cls("MISSED")]
        metrics = compute_metrics(clss)
        assert metrics["avoidable_pct"] == 75.0

    def test_returns_zero_pct_with_no_actionable(self):
        clss = [self._cls("OUT_OF_SCOPE")]
        metrics = compute_metrics(clss)
        assert metrics["avoidable_pct"] == 0
        assert metrics["caught_pct"] == 0

    def test_overall_coverage_pct(self):
        # 1 caught out of 2 total = 50%
        clss = [self._cls("CAUGHT"), self._cls("MISSED")]
        metrics = compute_metrics(clss)
        assert metrics["overall_coverage_pct"] == 50.0

    def test_total_pr_comments_count(self):
        clss = [self._cls("CAUGHT")] * 5
        assert compute_metrics(clss)["total_pr_comments"] == 5

    def test_empty_returns_all_zeros(self):
        metrics = compute_metrics([])
        assert metrics["total_pr_comments"] == 0
        assert metrics["avoidable_pct"] == 0


class TestIdentifyGaps:
    def _missed(self, comment_type="suggestion", file_path="foo.ts", body="fix this"):
        return {
            "classification": "MISSED",
            "comment_type": comment_type,
            "file_path": file_path,
            "comment_body": body,
        }

    def test_only_includes_missed_comments(self):
        clss = [
            self._missed(),
            {"classification": "CAUGHT", "comment_type": "inline", "file_path": "bar.ts", "comment_body": "ok"},
        ]
        gaps = identify_gaps(clss)
        assert sum(gaps["missed_by_type"].values()) == 1

    def test_groups_missed_by_type(self):
        clss = [self._missed("suggestion"), self._missed("suggestion"), self._missed("nitpick")]
        gaps = identify_gaps(clss)
        assert gaps["missed_by_type"]["suggestion"] == 2
        assert gaps["missed_by_type"]["nitpick"] == 1

    def test_groups_missed_by_file(self):
        clss = [self._missed(file_path="foo.ts"), self._missed(file_path="bar.ts")]
        gaps = identify_gaps(clss)
        assert "foo.ts" in gaps["missed_by_file"]
        assert "bar.ts" in gaps["missed_by_file"]

    def test_empty_returns_empty_dicts(self):
        gaps = identify_gaps([])
        assert gaps["missed_by_type"] == {}
        assert gaps["missed_by_file"] == {}
        assert gaps["suggested_guidelines"] == []
