# Generated by AI (PR Orchestrator)
"""Unit tests for merge_violations.py."""

import json
import os
import tempfile
from pathlib import Path

import pytest

from merge_violations import (
    _normalize_guideline,
    deduplicate,
    discover_iteration_reports,
    load_and_merge,
)


class TestNormalizeGuideline:
    def test_returns_short_name_from_full_windows_path(self):
        result = _normalize_guideline(r"D:\path\to\skills\dead-code-not-removed\SKILL.md")
        assert result == "dead-code-not-removed"

    def test_returns_short_name_from_relative_posix_path(self):
        result = _normalize_guideline("skills/dead-code-not-removed/SKILL.md")
        assert result == "dead-code-not-removed"

    def test_returns_already_short_name_unchanged(self):
        result = _normalize_guideline("dead-code-not-removed")
        assert result == "dead-code-not-removed"

    def test_returns_empty_string_unchanged(self):
        result = _normalize_guideline("")
        assert result == ""

    def test_returns_none_unchanged(self):
        result = _normalize_guideline(None)
        assert result is None

    def test_case_insensitive_skill_md_strip(self):
        result = _normalize_guideline("skills/my-guideline/SKILL.MD")
        assert result == "my-guideline"


class TestDeduplicate:
    def _make_violation(self, file_name, startline, guideline, iteration=1, **kwargs):
        return {
            "file_name": file_name,
            "startline": startline,
            "guideline": guideline,
            "_source_iteration": iteration,
            **kwargs,
        }

    def test_removes_exact_duplicates_keeping_earliest(self):
        v1 = self._make_violation("foo.ts", 10, "no-any", iteration=1)
        v2 = self._make_violation("foo.ts", 10, "no-any", iteration=2)
        result = deduplicate([v1, v2])
        assert len(result) == 1
        assert result[0]["_source_iteration"] == 1

    def test_increments_iteration_count_for_duplicates(self):
        violations = [
            self._make_violation("foo.ts", 10, "no-any", iteration=1),
            self._make_violation("foo.ts", 10, "no-any", iteration=2),
            self._make_violation("foo.ts", 10, "no-any", iteration=3),
        ]
        result = deduplicate(violations)
        assert result[0]["iteration_count"] == 3

    def test_keeps_distinct_violations(self):
        violations = [
            self._make_violation("foo.ts", 10, "no-any"),
            self._make_violation("foo.ts", 20, "no-any"),
            self._make_violation("bar.ts", 10, "no-any"),
        ]
        result = deduplicate(violations)
        assert len(result) == 3

    def test_empty_list_returns_empty(self):
        assert deduplicate([]) == []

    def test_result_sorted_by_file_then_line(self):
        violations = [
            self._make_violation("z.ts", 100, "rule-a"),
            self._make_violation("a.ts", 200, "rule-b"),
            self._make_violation("a.ts", 50, "rule-c"),
        ]
        result = deduplicate(violations)
        basenames = [(os.path.basename(v["file_name"]), v["startline"]) for v in result]
        assert basenames == [("a.ts", 50), ("a.ts", 200), ("z.ts", 100)]

    def test_single_violation_has_iteration_count_one(self):
        result = deduplicate([self._make_violation("foo.ts", 5, "rule")])
        assert result[0]["iteration_count"] == 1

    def test_distinguishes_by_guideline(self):
        violations = [
            self._make_violation("foo.ts", 10, "rule-a"),
            self._make_violation("foo.ts", 10, "rule-b"),
        ]
        result = deduplicate(violations)
        assert len(result) == 2


class TestDiscoverIterationReports:
    def test_finds_reports_sorted_by_iteration_number(self, tmp_path):
        for num in [5, 1, 3]:
            d = tmp_path / f"iteration-{num}"
            d.mkdir()
            (d / "final-review.json").write_text('{"violations":[]}', encoding="utf-8")

        reports = discover_iteration_reports(str(tmp_path))
        numbers = [r[0] for r in reports]
        assert numbers == [1, 3, 5]

    def test_skips_directories_without_final_review(self, tmp_path):
        (tmp_path / "iteration-1").mkdir()  # no final-review.json
        (tmp_path / "iteration-2").mkdir()
        (tmp_path / "iteration-2" / "final-review.json").write_text(
            '{"violations":[]}', encoding="utf-8"
        )

        reports = discover_iteration_reports(str(tmp_path))
        assert len(reports) == 1
        assert reports[0][0] == 2

    def test_skips_non_iteration_directories(self, tmp_path):
        (tmp_path / "other-dir").mkdir()
        (tmp_path / "other-dir" / "final-review.json").write_text(
            '{"violations":[]}', encoding="utf-8"
        )
        reports = discover_iteration_reports(str(tmp_path))
        assert reports == []

    def test_returns_paths_as_path_objects(self, tmp_path):
        d = tmp_path / "iteration-1"
        d.mkdir()
        (d / "final-review.json").write_text('{"violations":[]}', encoding="utf-8")
        reports = discover_iteration_reports(str(tmp_path))
        assert isinstance(reports[0][1], Path)


class TestLoadAndMerge:
    def _write_report(self, path: Path, violations=None, guidelines=None, files=None):
        data = {
            "violations": violations or [],
            "guidelines_reviewed": guidelines or [],
            "files_reviewed": files or [],
        }
        path.write_text(json.dumps(data), encoding="utf-8")

    def test_merges_violations_from_multiple_iterations(self, tmp_path):
        for num in [1, 2]:
            d = tmp_path / f"iteration-{num}"
            d.mkdir()
            self._write_report(
                d / "final-review.json",
                violations=[{"file_name": f"file{num}.ts", "guideline": "rule"}],
            )
        reports = [(1, tmp_path / "iteration-1" / "final-review.json"),
                   (2, tmp_path / "iteration-2" / "final-review.json")]
        result = load_and_merge(reports)
        assert len(result["all_violations"]) == 2

    def test_normalizes_file_name_to_basename(self, tmp_path):
        d = tmp_path / "iteration-1"
        d.mkdir()
        self._write_report(
            d / "final-review.json",
            violations=[{"file_name": "/long/path/to/foo.ts", "guideline": "rule"}],
        )
        reports = [(1, tmp_path / "iteration-1" / "final-review.json")]
        result = load_and_merge(reports)
        assert result["all_violations"][0]["file_name"] == "foo.ts"

    def test_normalizes_guideline_to_short_name(self, tmp_path):
        d = tmp_path / "iteration-1"
        d.mkdir()
        self._write_report(
            d / "final-review.json",
            violations=[{"guideline": "skills/my-rule/SKILL.md"}],
        )
        reports = [(1, tmp_path / "iteration-1" / "final-review.json")]
        result = load_and_merge(reports)
        assert result["all_violations"][0]["guideline"] == "my-rule"

    def test_collects_unique_guidelines_and_files(self, tmp_path):
        for num in [1, 2]:
            d = tmp_path / f"iteration-{num}"
            d.mkdir()
            self._write_report(
                d / "final-review.json",
                guidelines=["rule-a", "rule-b"],
                files=["foo.ts", "bar.ts"],
            )
        reports = [(1, tmp_path / "iteration-1" / "final-review.json"),
                   (2, tmp_path / "iteration-2" / "final-review.json")]
        result = load_and_merge(reports)
        assert set(result["guidelines_reviewed"]) == {"rule-a", "rule-b"}
        assert set(result["files_reviewed"]) == {"foo.ts", "bar.ts"}

    def test_tags_violations_with_source_iteration(self, tmp_path):
        d = tmp_path / "iteration-3"
        d.mkdir()
        self._write_report(
            d / "final-review.json",
            violations=[{"file_name": "foo.ts", "guideline": "rule"}],
        )
        reports = [(3, tmp_path / "iteration-3" / "final-review.json")]
        result = load_and_merge(reports)
        assert result["all_violations"][0]["_source_iteration"] == 3
