# Generated by AI (PR Orchestrator)
"""Unit tests for fetch_pr_comments.py — pure parsing functions."""

import pytest

from fetch_pr_comments import parse_pr_url


class TestParsePrUrl:
    # Azure DevOps dev.azure.com format
    def test_parses_ado_dev_azure_com_url(self):
        url = "https://dev.azure.com/myorg/myproject/_git/myrepo/pullrequest/42"
        result = parse_pr_url(url)
        assert result["platform"] == "azure-devops"
        assert result["org"] == "myorg"
        assert result["project"] == "myproject"
        assert result["repo"] == "myrepo"
        assert result["pr_id"] == 42

    def test_parses_ado_url_with_numeric_pr_id(self):
        url = "https://dev.azure.com/contoso/my-project/_git/my-repo/pullrequest/1234"
        result = parse_pr_url(url)
        assert result["pr_id"] == 1234

    def test_parses_ado_url_with_hyphenated_names(self):
        url = "https://dev.azure.com/my-org/my-project/_git/my-repo/pullrequest/7"
        result = parse_pr_url(url)
        assert result["org"] == "my-org"
        assert result["project"] == "my-project"
        assert result["repo"] == "my-repo"

    # Azure DevOps visualstudio.com format
    def test_parses_ado_visualstudio_url(self):
        url = "https://contoso.visualstudio.com/myproject/_git/myrepo/pullrequest/99"
        result = parse_pr_url(url)
        assert result["platform"] == "azure-devops"
        assert result["org"] == "contoso"
        assert result["project"] == "myproject"
        assert result["repo"] == "myrepo"
        assert result["pr_id"] == 99

    # GitHub format
    def test_parses_github_url(self):
        url = "https://github.com/azure-core/octane/pull/123"
        result = parse_pr_url(url)
        assert result["platform"] == "github"
        assert result["owner"] == "azure-core"
        assert result["repo"] == "octane"
        assert result["pr_id"] == 123

    def test_parses_github_url_with_hyphenated_owner(self):
        url = "https://github.com/my-org/my-repo/pull/5"
        result = parse_pr_url(url)
        assert result["owner"] == "my-org"
        assert result["repo"] == "my-repo"
        assert result["pr_id"] == 5

    # Error cases
    def test_exits_on_unrecognized_url(self):
        with pytest.raises(SystemExit):
            parse_pr_url("https://example.com/unknown/url")

    def test_exits_on_empty_string(self):
        with pytest.raises(SystemExit):
            parse_pr_url("")

    def test_exits_on_partial_github_url(self):
        with pytest.raises(SystemExit):
            parse_pr_url("https://github.com/azure-core/octane")
