<#
.SYNOPSIS
    Generates a PR build pipeline YAML for DocFX documentation validation.
.PARAMETER TargetRepo
    Root of the target repository.
.PARAMETER DocsPath
    Relative path to the docs directory (default: "docs").
#>
param(
    [Parameter(Mandatory = $true)]
    [string]$TargetRepo,

    [Parameter(Mandatory = $false)]
    [string]$DocsPath = "docs"
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $TargetRepo)) {
    throw "Target repository not found: $TargetRepo"
}

$TargetRepo = (Resolve-Path $TargetRepo).Path
$pipelinesDir = Join-Path $TargetRepo ".pipelines"
$pipelineFile = Join-Path $pipelinesDir "documentation-pr.yml"

if (Test-Path $pipelineFile) {
    Write-Host "  Skipped (exists): .pipelines/documentation-pr.yml" -ForegroundColor DarkGray
    return
}

if (-not (Test-Path $pipelinesDir)) {
    New-Item -ItemType Directory -Path $pipelinesDir -Force | Out-Null
}

$docsForward = $DocsPath -replace "\\", "/"

$content = @"
# Documentation PR Build
# Validates documentation builds cleanly on pull requests.
# Generated by Octane Documentation scenario.

trigger: none

pr:
  branches:
    include:
      - main
      - master
  paths:
    include:
      - $docsForward/**

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      packageType: 'sdk'
      version: '8.x'

  - script: |
      dotnet tool install -g docfx
      export PATH="`$PATH:`$HOME/.dotnet/tools"
      docs_root_path="`$(Build.SourcesDirectory)/$docsForward"
      echo "Building documentation at `$docs_root_path"
      cd "`$docs_root_path"
      docfx docfx.json --warningsAsErrors
    displayName: 'Build Documentation'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Documentation Site'
    inputs:
      PathtoPublish: '`$(Build.SourcesDirectory)/$docsForward/_site'
      ArtifactName: 'documentation-site'
    condition: succeededOrFailed()
"@

Set-Content -Path $pipelineFile -Value $content -Encoding UTF8
Write-Host "  Created: .pipelines/documentation-pr.yml" -ForegroundColor Green
Write-Host "  Next: set up a governed pipeline in StartRight pointing to this file." -ForegroundColor Yellow
